name: Build and Email APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Send APK to Gmail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: djizinluiz2@gmail.com
          password: jnux apya zevy rifw
          subject: "📦 Novo APK do IADJIZIN"
          body: "Segue em anexo o novo APK gerado automaticamente via GitHub Actions."
          to: djizinluiz2@gmail.com
          from: GitHub Actions 🤖 <djizinluiz2@gmail.com>
          attachments: build/app/outputs/flutter-apk/app-release.apk
