name: Build APK and Send Email

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Send email with APK
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: djizinluiz2@gmail.com
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: "✅ Seu APK do projeto IADJIZIN foi gerado com sucesso e está em anexo."
          to: djizinluiz2@gmail.com
          from: Djizin AI <djizinluiz2@gmail.com>
          content_type: text/html
          body: |
            <p>Olá Djizin,</p>
            <p>Seu APK do projeto <strong>IADJIZIN</strong> foi gerado automaticamente e está anexado neste e-mail.</p>
            <p>Abraço! 🤖</p>
          attachments: build/app/outputs/flutter-apk/app-release.apk
